apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: cv1simko-ambulance-ufe-content
spec:
  microFrontend: cv1simko-ambulance-ufe
  element:   cv1simko-ambulance-wl-app
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?cv1simko-ambulance-wl(/.*)?$"